### ISSUE TITLE
Add attributes as props

### ISSUE THREAD

**Issue by YoSev** [wobsoriano/vue-markdoc#2]
Hello,

is it possible to access the attributes added to markdown as props when adding a custom component like in your Callout.vue example?

Attributes are set as html paratmeters right now which makes them inaccessable:
![grafik](https://user-images.githubusercontent.com/1394374/203037727-713b533b-6c1b-42af-b894-df58000335e1.png)

Thanks

**Comment by YoSev** [comment]
Nevermind, i did not spend enough time to test it properly, it is working as expected.

**Comment by sirlan-ff00ff** [comment]
how did you get props to work?

I'm trying this library and just keep getting `Uncaught (in promise) TypeError: txtProp is undefined` when trying to use a component that expects a prop
