### ISSUE TITLE
Non-functional value encountered for default slot

### ISSUE THREAD

**Issue by YoSev** [wobsoriano/vue-markdoc#3]
Hello,

vue is complaining about the usage of the default slot with a non-functional value over a function slot.
Im not completely aware of what that means - Is this something that could be fixed within the rederer?

```
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance. 
  at <Callout type="warning" > 
  at <Anonymous> 
  at <Main onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref<Proxy { <target>: Proxy, <handler>: {…} }>>
  at <RouterView> 
  at <App>
```

**Comment by wobsoriano** [comment]
Do you have a repro? Thanks!

**Comment by YoSev** [comment]
I just created a fresh one with your example code:
https://github.com/john-dev/vue-markdown-test

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vue-markdoc/commit/720ce16b4f626321d57df1accee312faa2183452

**Comment by YoSev** [comment]
Thank you, i appreciate it!
