### ISSUE TITLE
Wrong (?) exported module path in package.json

### ISSUE THREAD

**Issue by maggiorante** [wobsoriano/vue-markdoc#6]
Hi,
I was trying to use your library (thanks for your work btw!) but encountered some problems trying to import it. If you take a look at the dist folder you'll see it contains a .js, .cjs and .d.ts files but no .mjs that is the one specified inside the package.json inside exports.import and module properties. Updaing them to use the .js seems to work fine instead.
Is this an error or expected behaviour?

Thanks for the help and any clarification!

Edit 1: My edits are as follows:
`"exports": {
    "require": "./dist/index.js",
    "import": "./dist/index.js"
  },
"module": "./dist/index.js",`

**Comment by wobsoriano** [comment]
Fixed! Thanks :)
